spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/thecloset
    username: thecloset
    password: capston
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
      cache: false
      prefix: classpath:/templates/

  jpa:
    databaseplatform:  org.hibernate.dialect.MariaDB102Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:
    cache: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


